### PR TITLE
Use current working directory for paths

### PR DESCRIPTION
**Pull request by m1-dev**
I used `path.resolve` with the current working directory and the constructor options. This is easier for ESM projects, since you don't have to declare a dirname variable and can just type `./src/commands` for example.

I've also used Prettier to format a _meta.json file, so new documentation pages can be added successfully.

### CODE REVIEW

**Review by notunderctrl — COMMENTED** [review]
Apologies for the delay. Got exams this week 😭 
I'll have to test the resolving of paths with this approach next week since I don't want it to introduce breaking changes.

**Comment by m1-dev** [comment]
> Apologies for the delay. Got exams this week 😭 
> 
> I'll have to test the resolving of paths with this approach next week since I don't want it to introduce breaking changes.

It's fine. I know about your exams.
This probably won't introduce anything breaking because `path.resolve` would still work when dirname is provided.

**Comment by notunderctrl** [comment]
> It's fine. I know about your exams.
> This probably won't introduce anything breaking because `path.resolve` would still work when dirname is provided.

Even when appended with the current working directory?

**Comment by m1-dev** [comment]
> Even when appended with the current working directory?

@notunderctrl Yeah, path.resolve is pretty good at this. Here's how I tested it:
```js
const path = require('path');
const getPath = (p) => path.resolve(process.cwd(), p);

console.log(getPath('./src')); // Full path
console.log(getPath(`${__dirname}/src`)); // Full path
```

**Pull request closed without merging**
