### PR TITLE
fix: i hate myself

### PR DESCRIPTION
**Pull request by twlite**

### CODE REVIEW

**Comment by twlite** [comment]
again, i trust my code since avraj is busy

**Comment by m1-dev** [comment]
nice title

**Comment by m1-dev** [comment]
> again, i trust my code since avraj is busy

@twlite did you remove the `watch triggered` message?

**Comment by twlite** [comment]
> > again, i trust my code since avraj is busy
> 
> @twlite did you remove the `watch triggered` message?

we test in prod once again

**Pull request merged**
